### ISSUE TITLE
Is the visualization tool in the depository? 

### ISSUE THREAD

**Issue by jimyang29** [tstarling/speckle#1]
Hello @tstarling ,

Very cool project, I just had a couple of questions. I found your [Laser speckle contrast page](https://tstarling.com/blog/2016/09/laser-speckle-contrast-imaging/) and I'm want to try reproducing an image similar to the one in your results section. I'm trying to understand how you processed the image into the one in the Results section. Later on the next section, you referred to a tool that will process the TIFF files.

I'm assuming that tool is the process in the "speckle-master\speckle-master\src\tools\process" and when I open the cpp file, I'm see that 

```c++
	options.width = width;
	options.height = height;
	options.bitsPerPixel = bitsPerSample;
	options.frameSize = height * width * bitsPerSample / 8;

	cv::Mat result;

	ComputePipeline compute(options);
	compute.writeFrame(&(buffer[0]), options.frameSize, result, CV_8UC3);

	cv::imwrite(outputName, result);
```

I am curious as to how you processed the image. I see that the 'outputName' will be the name of the processed image and the 'result' is the processed image. I'm guessing 'cv::Mat result' gets the image, and then the next line goes to the ComputePipeline.cpp file, where the actual processing occurs.

```c++
void ComputePipeline::writeFrame(void *data, size_t length, cv::Mat & output, int format) {
	if (length != m_options.frameSize) {
		throw std::runtime_error("Invalid frame length");
	}
	if (format != CV_8UC3 && format != CV_8UC4) {
		throw std::runtime_error("Invalid output format");
	}
	output.create(m_options.height, m_options.width, format);

	Mat3b * mat3;
	Mat4b * mat4;

	if (format == CV_8UC3) {
		mat3 = (Mat3b*)&output;
	} else {
		mat4 = (Mat4b*)&output;
	}

	m_unpack.startFrame(data);
	m_spatialWindow.startFrame();

	ComputePos pos;

	for (pos.y = 0; pos.y < m_options.height; pos.y++) {
		for (pos.x = 0; pos.x < m_options.width; pos.x++) {
			pos.outX = pos.outY = -1;
			int luminance = m_unpack.compute(pos);
			double kSq = m_spatialWindow.compute(pos, luminance);
			if (pos.outX == -1) {
				continue;
			}
			double x = m_correlationTime.compute(pos, kSq);
			cv::Vec3b c = m_visualize.compute(pos, x);
			if (format == CV_8UC3) {
				mat3->at<cv::Vec3b>(pos.outY, pos.outX) = c;
			} else {
				mat4->at<cv::Vec4b>(pos.outY, pos.outX) = cv::Vec4b(
					c[0], c[1], c[2], 0xff);
			}
		}
	}
}
```

Here is where I'm confused, I think the process occurs in the 'ComputePos' function, but for the image, you just change pos.outX and pos.outY to -1. There's then a reference to the SpatialWindow, and in that section it seems to correlate to the Mathematics section with the speckle contrast,k, as well as another reference to the 'correlationTime'. I can't seem to find the 'CV_8UC3' so is that where the processing occurs or is it a combination of these different functions?

Edit: I can't seem to get it to format all the code properly. Not sure why the code format is only formatting some of it. [TS edit: fixed it for you]

**Comment by tstarling** [comment]
Most of the magic is in SpatialWindow.cpp, which is invoked via m_spatialWindow.compute() in the code you quoted. By default, it takes the 49 pixels in a 7x7 window around the current location, and computes the variance. 

Unfortunately, this processing technique tends to highlight areas of high contrast in the input infrared image, it's not all that specific to laser speckle. The mathematical model assumes that the image is uniform except for the speckle. If you point it at your arm, you'll get 7x7 pixel fringes around high-contrast features like the borders of veins, which are much more visible in infrared than in visible light. TLSCI would not have this problem.

The other problem with this project was that the sensitivity to laser speckle is dependent on the exposure time, but there was no way to control the exposure time of the camera while it was still in the Kinect. For $120 you could buy an ArduCAM USB interface board to replace the Kinect in my project, which would allow exposure control of a cheap MT9M001 camera. Some software development would be needed to capture images from it.

CV_8UC3 is just a constant, it doesn't process anything. I used the OpenCV image processing library, and CV_8UC3 is the OpenCV constant specifying an image format consisting of 3 channels of 8 bit unsigned numbers, which is the normal RGB format.

**Comment by tstarling** [comment]
And in response to the question in the title, yes, everything I used is in the repository. I used tools/capture to capture images from the Kinect, and tools/process to generate the visualisation I used in my blog. You don't need to read or understand this code in order to use it, you just need to compile it.

**Comment by jimyang29** [comment]
Thanks, I'll look at the code again. My lab actually has a CCD camera and I was interested in seeing what I could do with it in regards with speckle imaging.

**Comment by tstarling** [comment]
Sounds good. My email address is tstarling@wikimedia.org, if you need any more help with this. I'd love to hear more about you and your project.
